#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Autostart apps
$HOME/.config/polybar/launch.sh
if [[ $(xrandr -q | grep 'HDMI-0 connected') ]]; then
	xrandr --output DP-0 --primary --mode 2560x1440 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --left-of DP-0
fi

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &

